### ISSUE TITLE
0.7.1 - unexpected query errors; platform dependent, seems to be related to EOL changes

### ISSUE THREAD

**Issue by peter-rando** [WebReflection/dblite#35] opened 2015-03-12 22:52 UTC
I've been struggling for days with what I _thought_ was my own problem in multiple chunks of db migration code.  I _think_ this issue may be related to the new EOL-related changes, and if so, they will likely affect more statements than just the CREATE TABLE IF NOT EXISTS, but I managed to get a very small bit of code that I believe is easy to work with and verify.

There is just one small bit of code, but I ran it in 4 ways/environments while testing.
1) Mac, using dblite 0.6.1
2) Mac, using dblite 0.7.1
3) Pi, using dblite 0.6.1
4) Pi, using dblite 0.7.1

```javascript
var dblite = require('dblite');
var db = dblite('users.db');

db.query( 'CREATE TABLE IF NOT EXISTS tester4 (doodie int)', function( err, data )
                {
                console.log( "create table err:--> " + err );
                console.log( "create table data:-->: " + data );

                db.query( 'SELECT count(*) FROM tester4', function( err, data )
                        {
                        console.log( "select err:--> " + err );
                        console.log( "select data: " );
                        console.dir( data );
                        process.exit();
                        } );
                } );
```
======== On Pi ; dblite 0.6.1 ========
> $ node tester.js
> create table err:--> null
> create table data:-->: undefined
> select err:--> null
> select data:
> [ [ '0' ] ]

======== On Pi ; dblite 0.7.1 ========
> $ node tester.js
> FINE
> create table err:--> null
> create table data:-->: undefined
> select err:--> null
> select data:
> [ [ '0' ] ]

Why is "FINE" being output here?  (and below, on Mac in 0.7.1)

======== On Mac ; dblite 0.6.1 ========
> create table err:--> null
> create table data:-->: undefined
> select err:--> null
> select data:
> [ { 'count(*)': '0' } ]

======== On Mac ; dblite 0.7.1 ========
> FINE
> create table err:--> Error: Error: near line 2: near "1": syntax error
> 
> create table data:-->: null
> 

(that's all, program terminates/hangs)
(same result using .withSQLite('3.8.6+'); )

Questions:
1) What is happening on the Mac in 0.7.1?  This is a show-stopper right now for us.  I've looking in the code a bit, and while I can't really follow what's happening, it looks like the db is being closed when it shouldn't be. (?)
2) Why the difference in default data return format between Pi and Mac?  This can be worked around, so not critical, but doesn't seem right.

**Comment by WebReflection** [comment] 2015-03-12 23:09
OK, the `FINE` should not have been there, and in version 0.7.2 is not there indeed (or shouldn't) .. looks like last push was without passing through the `make`, apologies for that. Now rading the rest and checking if there's anything else I should do but f the FINE was the problem, `0.7.2` solved it

**Comment by WebReflection** [comment] 2015-03-12 23:22
OK, testing on Mac right now after publishing `0.7.2` to npm .... I can run your test without FINE and without errors ... which Mac and/or node are you?

**Comment by peter-rando** [comment] 2015-03-12 23:28
Using node 0.10.24 at the moment, but have various versions installed.  Let me grab your update and see how it goes.

**Comment by WebReflection** [comment] 2015-03-12 23:33
I'm good on node `v0.12.0` and sqlite `3.8.5`

**Comment by peter-rando** [comment] 2015-03-12 23:35
I still get this:
create table err:--> Error: Error: near line 2: near "1": syntax error
create table data:-->: null
------------------
I don't see the "FINE" output anymore, but wasn't that inside the program.on('close'...) function?  So it seems like the "FINE" output would have been helpful debugging, but in any case the code got a "close" event, right?  Still getting that.

**Comment by peter-rando** [comment] 2015-03-12 23:36
sorry about the formatting.  never used this system, and rushing to comment while you're here.
We are using sqlite3 v3.7.15, and node 0.10.24, though I can try with 0.10.28 easily.

**Comment by WebReflection** [comment] 2015-03-12 23:36
now on sqlite 3.8.8.3 ... maybe the problem is the node version .... oh well ..

**Comment by WebReflection** [comment] 2015-03-12 23:39
also via `uname =a` Darwin Kernel Version 14.1.0 .... which Mac are you? I start thinking the problem is in your outdated sqlite (yeah, maybe the latest dblite found a gotcha in it, but what it does that EOL change is a feature detection .... that should NOT fail ... damn it me!)

**Comment by peter-rando** [comment] 2015-03-12 23:41
update: ran with node 0.10.28, still same issue.  

for debugging purposes i can download a v0.12 node and give that a try, though making a jump like that for production would not be a trivial decision.  at least another data point.  can you run in an earlier node or sqlite?

**Comment by WebReflection** [comment] 2015-03-12 23:41
OK, apologies but I have to go (to sleep, midnight here) but I'll check against any extra info you can give me. Thanks and sorry for any trouble caused

**Comment by WebReflection** [comment] 2015-03-12 23:43
no, cannot find any older sqlite .. I think the problem is there. If you have an sqlite3 executable for Mac 64bit please send it to me at my name dot surname gmail com , thank you

**Comment by peter-rando** [comment] 2015-03-12 23:43
the fast response is great.  i have a little more to go on right now, and will definitely continue posting here as i go.  still early-ish here. :-)    new node is downloading as i type.

**Comment by peter-rando** [comment] 2015-03-12 23:46
For better or worse, node 0.12.0 doesn't help.  That most likely means some sqlite3 minor revision issue.  Time to go exploring...

**Comment by peter-rando** [comment] 2015-03-13 00:29
I downloaded a newer version of sqlite3 (3.8.8.3).  Not ready to overwrite the existing version we're using, but I set a direct path as follows, to the binary, which appears to be fully functional.  Added like this:

> var dblite = require('dblite');
> dblite.bin = '/path/to/my/updated/copy/of/sqlite3';
> var db = dblite('users.db');

Still get the same response, i.e. I think the 'close' event is firing prematurely somehow. (?)

I wasn't sure how to verify that the newer sqlite is actually running, but I edited the path and added a (bogus) 'x', so '/path/to/.../sqlite3x';  and it failed, saying "invalid executable:", so I'm pretty confident that I was in fact running the new sqlite3, and still getting the same error.  Also tried this with node 0.10.28 and 0.12.0.

Now I'm kind of stuck.  I am running on an older Darwin, but that's not an option for me to update, and it seems like quite a stretch to think that would be causing something like this.  Would be nice to find another computer to test on, but that will be a bigger project...

As for an sqlite3 executable, what I have was brew-installed, so I'm not sure if there's a single, simple file to send.  In any case, I was able to use 3.8.8.3 here, so that seems to indicate that's not the problem.

Last question for the moment: do you know why v0.6.1 output different default format on Pi and Mac?  It doesn't seem very likely related, but it is (was) another case where output was different on Mac.

Thoughts?

**Comment by peter-rando** [comment] 2015-03-13 07:43
I ran a few more tests tonight.  All with node 0.10.28 and Sqlite3 3.8.8.3.

> Machine 1; Mac Mini ; 10.8
> os.type() --> Darwin
> os.release() --> 12.2.0
> os.arch() --> x64
> os.cpus() --> 'Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz' (x2)

Test works fine.  So let's find an older machine.


> Machine 2 ; older 2.16GHz MacBook ; 10.7
> os.type() --> Darwin
> os.release() --> 11.4.0
> os.arch() --> ia32
> os.cpus() --> 'Intel(R) Core(TM)2 CPU         T7400  @ 2.16GHz' (x2)

Test works fine!


Puzzling. Let's get more info back on the dev machine

> Machine 3 ; 2.53GHz MacBook Pro ; 10.6
> os.type() --> Darwin
> os.release() --> 10.8.0
> os.arch() --> ia32
> os.cpus() --> 'Intel(R) Core(TM)2 Duo CPU     P8700  @ 2.53GHz' (x2)

Test FAILS! :-(


So it's not the processor, but maybe something in Darwin itself??  That seems very strange given the nature of this runtime environment, but at the moment I have no other explanation.

But here's a question for you: What changed between dblite 0.6.x and 0.7.x that could have this kind of effect?  Because 0.6.x didn't prematurely close on my dev machine, but it did return the data back in a different format than either Pi or newer Mac.  Could it be related?

**Comment by WebReflection** [comment] 2015-03-13 09:25
do you mind checking version `0.7.3` I've just pushed? Thanks

**Comment by WebReflection** [comment] 2015-03-13 09:30
also , about differences ... sqlite is apparently the most inconsistent built thing ever. While it's rock solid, there are so tiny little details between versions and OSes I don't know where to start. Why the Pi is different? Probably because that version has been built with a smarter syntax parser while the Mac thinks there should not be an implicit numeric result there and it put `count(*)` as field name. I cannot reproduce that but I am pretty sure that if you try `SELECT COUNT(*) AS total FROM tester4` you'll have a consistent result. Always use aliases would be my suggestion.

**Comment by WebReflection** [comment] 2015-03-13 10:00
so, let's hope this is good news. I've installed OSX Lion on my old Mac mini and tested your initial example, this is the result:

```
create table err:--> null
create table data:-->: undefined
select err:--> null
select data: 
[ [ '0' ] ]
```

and this is the `uname -a` 

```
uname -a
Darwin Andreas-Mac-mini.local 11.0.0 Darwin Kernel Version 11.0.0: Sat Jun 18 12:56:35 PDT 2011; root:xnu-1699.22.73~1/RELEASE_X86_64 x86_64
```

Please close this if everything is OK in your machine too. Thank you and apologies for any inconvenient caused with the `0.7.1`, I wish I could test all platforms as I do with browsers related things.

Cheers

**Comment by WebReflection** [comment] 2015-03-13 10:01
forgot to mention that was node `0.12` on sqlite `3.7.5` , this should be a similar setup you have

**Comment by WebReflection** [comment] 2015-03-13 10:15
actually realized now your failing machine is on `10.8` and not `11` ... the change I've made is in the definition of `EOL` when if there is a syntax error with the select it assumes automatically that the correct `EOL` is `\n` which is what all your systems where using before ( unless you where using newer sqlite and the new trick )

This `EOL` thing has been problematic since ever and it keeps changing, my hope was that with latest changes the program would have been smart enough to figure it out and "just work" ... but of course some weird alchemy on older macs screwed it so let's hope this internet recovery on a Mid 2010 Mac mini will put a `10.8` on it so I can test that OS too.

After this test I'm afraid I don't think there's really anything else I could do.

**Comment by WebReflection** [comment] 2015-03-13 11:13
too bad that gave me an 11.4.2 kernel, so I've finished with things I can do. Looking forward for your test.

**Comment by peter-rando** [comment] 2015-03-13 15:34
We are in very different time zones!  Appreciate the help, unfortunately, it didn't fix things.

Reading through your details now, want to try to digest everything.  

I did double-check the EOL char via node's os.EOL and it shows '\n' on all machines here.  So at least as far as node is concerned, that's the same.  

Darwin 10.8.0 is MacOS 10.6.8 (crazy mismatched numbering scheme!), which is the very last version of MacOS that runs some necessary legacy software we need (via rosetta), so unfortunately, it's not possible to upgrade this machine!  It's not that old! ;-)  10.6.8 update was released in July 2011, so it's really only a bit over 3.5 years ago.

I do understand the difficulties in trying to debug something when you don't have a machine to test on directly.  That said, I'm more than happy to shoot you any information here that I can, like perhaps specific details on what sqlite3 spits out?  

I'll try your 0.6.x alias suggestion now as well...

**Comment by peter-rando** [comment] 2015-03-13 16:01
FYI, in 0.6.1, using 'SELECT count(*) AS total FROM tester4', still get:

> ==== TEST 3 Mac ====
> create table err:--> null
> create table data:-->: undefined
> select err:--> null
> select data: 
> [ { total: '0' } ]

I really wonder if this is related...

**Comment by WebReflection** [comment] 2015-03-13 16:14
OK that is bizarre ... it looks like you have `var db = dblite('users.db', '-header');` instead of just `var db = dblite('users.db');` ... why would that be is a mistery.

Can you please write this in console? `sqlite3 -csv` and once in, `SELECT 1;` and press enter. You should have just `1` as output.

After that, write `.exit` and enter

**Comment by WebReflection** [comment] 2015-03-13 16:16
attached how it should look like
![screenshot from 2015-03-13 16 16 01](https://cloud.githubusercontent.com/assets/85749/6642406/47fc7e28-c99c-11e4-90ca-88de7c457060.png)

**Comment by WebReflection** [comment] 2015-03-13 16:22
also, in case that does not work, can you please try your first example with `var db = dblite('users.db', '-noheader');` and see if forcing no headers improves anyhow ? If that's the problem, it's easy to fix. Fingers crossed

**Comment by WebReflection** [comment] 2015-03-13 16:30
OK, just to play it safe, I've forced `"-noheader"` in version `0.7.4` and hopefully that should solve the problem ... got a bad feeling though

**Comment by peter-rando** [comment] 2015-03-13 16:35
> SQLite version 3.7.15 2012-12-12 13:36:53
> Enter ".help" for instructions
> Enter SQL statements terminated with a ";"
> sqlite> select 1;
> 1
> 1
> sqlite> .exit

weird!  double "1".  let me try in the newer version of sqlite3 as well...

**Comment by WebReflection** [comment] 2015-03-13 16:37
no,  please just try latest `dblite` that should solve that problem ... and please try on eldest `3.5.x` version you have, thank you

**Comment by WebReflection** [comment] 2015-03-13 16:38
I meant 3.7.x ...

**Comment by peter-rando** [comment] 2015-03-13 16:40
progress!  let me organize my thoughts here for a minute...

**Comment by peter-rando** [comment] 2015-03-13 16:45
I first tried `sqlite3 -csv` and got the result above.  Then tried `sqlite3 -csv -noheader`, from your clue above.  The difference was the "double 1" vs a "single 1", which looked promising.  

So then I grabbed your 7.4 update and ran it and got a real result!  As follows:

> ==== TEST 3d Mac ====
> create table err:--> null
> create table data:-->: undefined
> select err:--> null
> select data: 
> [ { v: '4' } ]

I don't know why the data is returned as an object, rather than an array, but that's something that we can either work around here, or I can help you determine for the library's general well-being. :-)

**Comment by WebReflection** [comment] 2015-03-13 16:47
you need to explicitly initialize the db with `'-noheader'` because your system for whatever reason uses headers by default. 

`var db = dblite('users.db', '-noheader');`

**OR** you need to perform a query at the very beginning such

`db.query('.headers off');`

and then keep working

**Comment by peter-rando** [comment] 2015-03-13 16:49
Also, just to let you know, this -noheader update appears to fix the main problem for both the older (3.7.15) and newer (3.8.8.3) sqlite.

**Comment by WebReflection** [comment] 2015-03-13 16:53
This is very weird, what happens if you just enter `sqlite3 -csv` and type `.show` ?

```
sqlite3 -csv
SQLite version 3.8.8.3 2015-02-25 13:29:11
Enter ".help" for usage hints.
sqlite> .show
        echo: off
         eqp: off
  explain: off
     headers: off
        mode: csv
   nullvalue: ""
      output: stdout
colseparator: ","
rowseparator: "\n"
       stats: off
       width: 
sqlite> .exit
```

By default, accordingly with the manual, that should be false.

![screenshot from 2015-03-13 16 51 17](https://cloud.githubusercontent.com/assets/85749/6643071/7d6f55e4-c9a1-11e4-93ce-869acfdca149.png)

**Comment by peter-rando** [comment] 2015-03-13 16:54
`... got a bad feeling though`

But a better feeling now, right?  I know I do!  

The good thing about a fix like this is that it's not really hacking up the code to put in special cases for different systems.  Sometimes that's necessary, of course, but never pretty.  This seems like an easy mod that shouldn't have any bad effects on any other system, and in fact might save someone else from problems if some future build of sqlite behaves unusually on some other platform.

**Comment by WebReflection** [comment] 2015-03-13 16:56
I've fixed the initialization, not the fact I should explicitly force everything to have `-noheaders` ... but actually I am going to do that in case `-header` option has been passed already.

**Comment by WebReflection** [comment] 2015-03-13 17:01
can you pleaase double check that `0.7.5` works as expected? Thank you

**Comment by peter-rando** [comment] 2015-03-13 17:04
I am embarrassed.  I could just run away and hide, but I would rather fess up and be open.  The `.show` exercise above led me to find that an .sqliterc file in one's home directory will override those defaults, and yes, I had one. If there was a red-face emoticon handy I'd use it right now.  The file has apparently been there for eons and I had forgotten that such a thing was even possible, let alone that I must have created it when first installing and learning sqlite.

The update you made, explicitly forcing `-noheader` is still probably a good idea, or at least not a bad thing to have in place.

**Comment by peter-rando** [comment] 2015-03-13 17:07
Holy cow.  Did you fix something else in 0.7.5, or did I have other testing stuff in place blocking this:

> ==== TEST 3f Mac ====
> create table err:--> null
> create table data:-->: undefined
> select err:--> null
> select data: 
> [ [ '4' ] ]

:-)

**Comment by WebReflection** [comment] 2015-03-13 17:10
yeah ... but you see now where is the problem? Beside you forgetting that file, that **is** an explicit override of intents so while I still need to force no headers to understand the real EOL char which might not be the one specified in the `.show`, due `-csv` flag and the standard that in some case wants `\r\n` regardless (old bug/story here), forcing `noheader` might have undesired side effects for others.

I'll be patiently waiting here hoping nobody wll get hurt by `0.7.5` but honestly I think `dblite` shold be consistent and developers eventually explicit if they want `-header` passing it as second argument.

That leads to the least surprise, which is the reason we are here now ... you were surprised by inconsistent library behavior.

Now `0.7.5` opens in `-noheader` unless differently specified.

Please close if you think we are good. Thank you

**Comment by peter-rando** [comment] 2015-03-13 17:22
Yes indeed, the least surprising behavior is best, though in fairness it does seem that I was overriding default settings. :-(

I hope this doesn't bite anyone else the other direction, but you have far better insights into that than I do at this point.  Perhaps it's worth dropping some small note into the README Updates section?  (oh, and there's a typo there, it says "Upadtes" now)

My dev setup right now is in quite the disarray from all this testing.  Let me try to clean everything up, make sure I have everything reset back to known conditions, etc., and do a little double-checking, then I'll be happy to close this out.

**Comment by WebReflection** [comment] 2015-03-13 17:31
updated typo and info https://github.com/WebReflection/dblite#updates

**Comment by peter-rando** [comment] 2015-03-13 18:29
Updates updated. Check. :-)

Separately, this isn't really an "issue" per se, but as long as we're here, could you answer a question that I've had for a while?  Not sure where else might be more appropriate to ask, and as I'm cleaning up, it's gnawing at me.

Regarding a/synchronous behavior, if no callback is specified, can we depend on the statement being synchronous?  I've read the docs describing the callback function, and I've skimmed through the code, and I'm still not totally clear.  

For example:

	db.query( 'CREATE TABLE IF NOT EXISTS tester (version int)' );
	db.query( 'INSERT INTO tester (version) values (5)' );
	db.query( 'SELECT version FROM tester', function( err, data )
		        {
		        console.log( "select err:--> " + err );
		        console.log( "select data: " );
		        console.dir( data );
		        process.exit();
		        } );

seems to work perfectly fine ( now! :-) ), aside from checking for errors, but there are other ways to manage that, especially during initialization.  But I don't want to count on that behavior without knowing for sure.  Currently we have complex (ugly) layers of nested callbacks, as is typical to node in general, but much of it is initialization code, which is fine to run synchronously -- IF we know we are guaranteed that each statement will finish in order.

**Comment by peter-rando** [comment] 2015-03-13 20:53
Oddly, I can't seem to load any of the recent dblite updates **on a Pi**, even though they load fine on Mac.  I've not seen this before.  I can load v0.6.x or v0.7.x (which gets 0.7.1), so npm appears to be working.

Just fyi, taking a break now, will return in maybe an hour.

**Comment by peter-rando** [comment] 2015-03-13 22:52
I tar'd and manually xfer'd 0.7.5 from Mac to Pi, just to make sure I exercised it at least once on Pi.  Would be nice to know why my Mac npm sees this latest version but Pi npm does not.  Both are npm 1.4.9.  Not sure if this is something you can verify or not.

That said, and even considering I haven't had a chance to *thoroughly* test this update, given the contained nature of the fix I'm fine closing this if you are.  I'll hold off for now though, just to make sure you have a chance to read my question above about sync/async, otherwise the thread might die and you'll never see it! ;-)

**Comment by WebReflection** [comment] 2015-03-13 23:55
I'll close this for you.

Answering questions:

  * you can use the multiple `.query` way and be sure that nothing is executed until the previous query is done 'cause that's how dblite works, it queues everything, no way you can have a late query running after an earlier one
  * you can chose to do things nested per each query resutl inside the related callback ... or, you can have a `Promises` like approach simply keep queuing queries as you would do with `.then` ... all you have to do is set an `error` listener so that whenever that occurs you can either fail soon and safely or do anything else you want to
  * no, I don't have control over `npm` and there's nothing I can do. If i uses some sort of cache, well, by this time it should have gone anyway. I cannot reproduce what you say in my various PIs ( old model and most recent one ) so no idea, also if you `npm info dblite` you'll see the `0.7.5` listed

Cheers

**Closed by WebReflection** 2015-03-13 23:55 UTC

**Comment by peter-rando** [comment] 2015-03-14 07:26
Regarding the synchronous nature of dblite when no callback is present, that's what I thought (and hoped), but I really couldn't tell for sure.  It all makes sense, and seems like a nice implementation -- perhaps if you included something in the callback:function section that made that very explicit it might be helpful for others.

re: npm, no problem, I'll pursue that separately.  Just FYI, I'm still getting this with `npm info dblite`:
	....snip....
	     '0.6.0': '2014-08-19T14:37:56.587Z',
	     '0.6.1': '2014-08-19T14:44:31.419Z',
	     '0.7.0': '2015-02-25T10:36:17.913Z',
	     '0.7.1': '2015-03-07T22:01:19.948Z' },
	  author: 'Andrea Giammarchi (http://webreflection.blogspot.com/)',
	  repository: 
	   { type: 'git',
	     url: 'git://github.com/WebReflection/dblite.git' },
	  homepage: 'https://github.com/WebReflection/dblite',
	  keywords: 
	   [ 'sqlite',
	....snip....
	     'spawn' ],
	  bugs: { url: 'https://github.com/WebReflection/dblite/issues' },
	  license: 'MIT',
	  readmeFilename: 'README.md',
	  version: '0.7.1',
	  engine: 'node >= 0.6.0',
	  main: './build/dblite.node.js',
	  scripts: { test: 'node test/.test.js' },
	  gitHead: 'd582e5f324173fbb335525aded343cefbcc3a020',
	  dist: 
	   { shasum: 'caa00e9d4549468d13bea521af3b9784d6eba85d',
	     tarball: 'http://registry.npmjs.org/dblite/-/dblite-0.7.1.tgz' } }

Seems far too long for a caching issue, but like I said, I'll pursue separately, and worst case I can always manually move from one machine to another here.

In closing, I commend you on this package.  For our use with Pi (which I noticed you are also doing!), it seems "just right".  Efficient, and by its very nature, easy to work with, and mostly easy-to-understand.  And your responsiveness here has been superb.  Thank you and I'm closing as well.

**Comment by WebReflection** [comment] 2015-03-14 10:28
just tested on my Pi via `npm info dblite` and `0.7.5` is there. About the Pi, this package was born in order to avoid gyp compilation that was not possible in linino or OpenWRT and MIPS board, and since it worked well there on 400Mhz MIPS architecture and 64MB which is way less power even than Pi A it came out it was ideal for the Pi too. It decouple the SQLite dependency and hopefully it's robust. I am not sure why it says only 3 packages depends on it, 'cause those 1.200 monthyl downloads suggest people really use this package a lot but maybe they just install it globally once and forget about it in other projects? Who knows ... glad we solved this though, each path is making this package better!

Best Regards
